spring:
  datasource:
    url: jdbc:mysql://localhost:3306/moveon
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
        # -------------------- geo.point 사용하기 위해 추가 -----------------------------
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect
  data:
      redis:
        host: localhost
        port: 6379
naver:
  apiKeyId: 
  apiKey:
geocoding:
  api: 
